apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app-namespace.yaml
- department-deployment.yaml
- organization-deployment.yaml

namespace: argocd-sample-app
images:
- name: organization-image
  newName: harbor.tanzu.be/library/iso-organization-service
  newTag: b38.20211006.180013

- name: department-image
  newName: harbor.tanzu.be/library/iso-department-service
  newTag: b38.20211006.175956
