apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- app-namespace.yaml
- department-deployment.yaml
- organization-deployment.yaml
- mongodb-configmap.yaml
- mongodb-secret.yaml

namespace: argocd-sample-app
images:
- name: organization-image
  newName: harbor.tanzu.be/library/iso-organization-service
  newTag: b48.20211006.224312

- name: department-image
  newName: harbor.tanzu.be/library/iso-department-service
  newTag: b48.20211006.224351